# **2. Matrix Multiplication in PyTorch**


Matrix multiplication is essential for neural networks! PyTorch provides efficient operations for multiplying matrices and tensors.

In [ ]:
import torch

# **1.Matrix Multiplication**

In [ ]:
# We use @ operator for matrix multiplication and we use torch.matmul


print("Matrix Multiplication By @operator ...")
A = torch.tensor([[1,2],[3,4]])

B = torch.tensor([[5,6],[7,8]])

print(A @ B)

print("Matrix Multiplication By MatMul...")
mat_mult = torch.matmul(A,B)
print(mat_mult)
# print(type(mat_mult))

Matrix Multiplication By @operator ...
tensor([[19, 22],
        [43, 50]])
Matrix Multiplication By MatMul...
tensor([[19, 22],
        [43, 50]])
<class 'torch.Tensor'>


# **# 2. MatrixVector Multiplication**

In [10]:
M = torch.tensor([[1,2],[3,4]],dtype = torch.float32)
print(M)
print(M.shape)

V = torch.tensor([5,6],dtype = torch.float32)

print(V)
print(V.shape)

result = M @ V
print("M @ V matrix-vector Multiplication :")
print("\n result :",result)
print(result.shape)


tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
tensor([5., 6.])
torch.Size([2])
M @ V matrix-vector Multiplication :

 result : tensor([17., 39.])
torch.Size([2])


# **3. Batch Matrix Multiplication**

In [18]:
batch_a = torch.randn(3,2,4)
batch_b = torch.randn(3,4,3)
print("The batch_a Matrix ")
print(batch_a)
print(batch_a.shape)

print("The batch_b matrix ")
print(batch_b)
print(batch_b.shape)


print("The multiplication b/w  A and B ")
batch_result = torch.bmm(batch_a,batch_b)
print(batch_result)

# A0 = batch_a[0]
# B0 = batch_b[0]

# result0 = A0 @ B
# print(result0)

The batch_a Matrix 
tensor([[[-0.5725,  0.6228, -1.3717,  0.3211],
         [-1.9376, -1.0981, -0.5284,  0.8694]],

        [[-0.3334, -1.0170, -1.5387, -0.8206],
         [ 0.7243, -0.9463, -0.0465, -0.6945]],

        [[-0.5170,  0.8367,  0.7324, -0.8040],
         [ 1.1431, -0.0934, -1.0742, -0.0655]]])
torch.Size([3, 2, 4])
The batch_b matrix 
tensor([[[-0.2750, -0.3780, -0.2460],
         [-0.5563, -0.3060, -1.1697],
         [ 0.0866, -0.9397, -0.8762],
         [-0.8317, -0.3579, -1.5609]],

        [[ 0.9667,  0.7069,  0.4648],
         [-2.2454,  1.6472, -0.9244],
         [-0.5480,  1.2071, -0.3075],
         [ 1.1103, -0.7301, -1.0768]],

        [[ 1.0997,  1.0173, -0.1885],
         [ 0.1607, -0.5194, -0.2006],
         [-0.1776, -1.1152, -0.5350],
         [ 1.3669, -0.6482, -0.6170]]])
torch.Size([3, 4, 3])
The multiplication b/w  A and B 
tensor([[[-0.5748,  1.1999,  0.1131],
         [ 0.3750,  1.2537,  0.8671]],

        [[ 1.8935, -3.1692,  2.1420],
         [ 2.0794

# **4. Element-wise Multiplication**

In [17]:
A = torch.tensor([[1,2],[3,4]],dtype = torch.float32)
print("\n The matrix A ",A)
B = torch.tensor([[5,6],[7,8]],dtype = torch.float32)
print("\n The matrix B ",B)
print("The Element wise matrix Multiplication B/W A and B ...")
print(A * B)


 The matrix A  tensor([[1., 2.],
        [3., 4.]])

 The matrix B  tensor([[5., 6.],
        [7., 8.]])
The Element wise matrix Multiplication B/W A and B ...
tensor([[ 5., 12.],
        [21., 32.]])
