Pytorch Beginning ....


# **Tensors are like arrays in NumPy, but designed for deep learning! They can store numbers and perform operations efficiently on GPUs.**

In [3]:
#Creating Tensors
import torch as pt
t1 = pt.tensor([1,2,3,4,5])
print('1D Tensor :',t1)
print(f"Shape :{t1.shape}")
print(f"Size :,{t1.size()}")

1D Tensor : tensor([1, 2, 3, 4, 5])
Shape :torch.Size([5])
Size :,torch.Size([5])


In [4]:

#creating a 2D matrix

t2 = pt.tensor([[1,2,3],[4,5,6]])
print("Tensor-2D:",t2)

print("shape",t2.shape)
print("Size",t2.size())

Tensor-2D: tensor([[1, 2, 3],
        [4, 5, 6]])
shape torch.Size([2, 3])
Size torch.Size([2, 3])


In [5]:
#3D tensor
print("3D-Tensor")
t3 = pt.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(t3)

print(f"Shape :",t3.shape)
print(f"no .of .dimensions :",t3.dim())


3D-Tensor
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Shape : torch.Size([1, 3, 3])
no .of .dimensions : 3



# **2. Creating Tensors with Zeros and Ones**

In [14]:
#Create a tensor Filled with Zeroes and Ones

zeros_1d = pt.zeros(5)
print("1D Tensor of Zeros :")
print(zeros_1d)
print()

zero_2d = pt.zeros(3,4)
print("2D tensor of zeroes (3 rows and 4 cols)")
print(zero_2d)

#Now time to create the tensors filled with ones

ones_1d = pt.ones(5)
print("\n 1D Tensors of Ones  :",ones_1d)

#2d tensors ....

tensors_2d = pt.ones(4,4)
print("\n 2d tensors of ones :",tensors_2d)



1D Tensor of Zeros :
tensor([0., 0., 0., 0., 0.])

2D tensor of zeroes (3 rows and 4 cols)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

 1D Tensors of Ones  : tensor([1., 1., 1., 1., 1.])

 2d tensors of ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


# **3. Creating Tensors from NumPy Arrays**

In [18]:
# Creating a new Array ...
import numpy as np
np_array = np.array([1,2,3,4,5])
print("Numpy Array ")
print(np_array)
print(type(np_array))

#converting to pytorch tensor

torch_array = pt.from_numpy(np_array)
print("\n numpy array to pytorch  :")
print(torch_array)
print(type(torch_array))


#convert pytorch array to numpy
array_back = pt.tensor([1,2,3,4,5])
np_array_back = array_back.numpy()
print("\n Converted Bak to Numpy :")
print(np_array_back)
print(type(np_array_back))


# Note: They share memory if using from_numpy()!
print("Note: torch.from_numpy() shares memory with NumPy array!")
print("Changes to one affect the other (unless you use .clone())")

Numpy Array 
[1 2 3 4 5]
<class 'numpy.ndarray'>

 numpy array to pytorch  :
tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>

 Converted Bak to Numpy :
[1 2 3 4 5]
<class 'numpy.ndarray'>
Note: torch.from_numpy() shares memory with NumPy array!
Changes to one affect the other (unless you use .clone())



# **4. Creating Tensors with Random Values**

### Generate random tensors for initializing neural networks!

In [29]:
# random values b/w 0 and 1


random_tensor = pt.rand(3,4)
print("Random tensor (values between 0 and 1):")
print(random_tensor)

#random Integers
random_int = pt.randint(0,11,(4,4))
print("\n Random Intgers (0 to 9 ) :")
print(random_int)

#random values from normal distribution (mean=0, std=1)
normal_tensor = pt.randn(4,4)
print("\n Random values from normal distribution:")
print(normal_tensor)


# Random values with specific range
random_range = pt.rand(3, 4) * 10  # Scale to 0-10
print("\n Random values scaled to 0-10:")
print(random_range)

Random tensor (values between 0 and 1):
tensor([[0.6418, 0.5540, 0.8565, 0.6912],
        [0.4589, 0.5832, 0.6035, 0.8265],
        [0.0470, 0.1196, 0.1059, 0.0067]])

 Random Intgers (0 to 9 ) :
tensor([[2, 7, 6, 8],
        [3, 3, 9, 6],
        [0, 4, 3, 8],
        [6, 5, 1, 7]])

 Random values from normal distribution:
tensor([[-1.3196, -1.0763, -0.8581,  0.2975],
        [-0.3703, -1.1699,  1.9709, -0.5713],
        [ 0.9184, -1.0891,  0.2832, -0.4354],
        [ 0.6812, -0.4007,  0.4123,  0.8810]])

 Random values scaled to 0-10:
tensor([[9.9733, 2.2343, 1.9645, 7.3937],
        [9.9714, 0.3459, 7.0380, 0.8243],
        [6.0730, 1.8489, 4.3274, 1.7785]])


# 5.Data Types



In [39]:
# Default float tensor

t_float = pt.tensor([1.0,2.0,3.0])
print("Float Tensor :",t_float)
print(type(t_float))

#Integer Tensor
t_int = pt.tensor([1,2,3],dtype = pt.int64)
print("\n Integer Tensor :")
print(t_int)

#Float 32 Tensor (most common for neural networks)
t_float32 = pt.tensor([1.0, 2.0, 3.0], dtype=pt.float32)
print("\n Float32 tensor:")
print(t_float32)
print(f"dtype: {t_float32.dtype}")
print()

#convert b/w types

t_convert = pt.tensor([1,2,3],dtype = pt.int64)
print(t_convert)
print(type(t_convert))
t_float_convert = t_convert.float()
print(t_float_convert)
print(t_float_convert.dtype)

print("Converted Tensor from int to float ")

# Common dtypes
print("\n Common dtypes:")
print(f"torch.float32 (or torch.float): 32-bit float")
print(f"torch.float64 (or torch.double): 64-bit float")
print(f"torch.int32 (or torch.int): 32-bit integer")
print(f"torch.int64 (or torch.long): 64-bit integer")


Float Tensor : tensor([1., 2., 3.])
<class 'torch.Tensor'>

 Integer Tensor :
tensor([1, 2, 3])

 Float32 tensor:
tensor([1., 2., 3.])
dtype: torch.float32

tensor([1, 2, 3])
<class 'torch.Tensor'>
tensor([1., 2., 3.])
torch.float32
Converted Tensor from int to float 

 Common dtypes:
torch.float32 (or torch.float): 32-bit float
torch.float64 (or torch.double): 64-bit float
torch.int32 (or torch.int): 32-bit integer
torch.int64 (or torch.long): 64-bit integer


# 6. Key Takeaways

# Creating tensors:

torch.tensor([...]) - from list

torch.zeros(shape) - filled with zeros

torch.ones(shape) - filled with ones

torch.rand(shape) - random values (0-1)

torch.randn(shape) - random from normal distribution

torch.from_numpy(array) - from NumPy array

# **Important properties:**


tensor.shape - dimensions of tensor

tensor.dtype - data type (float32, int64, etc.)

tensor.dim() - number of dimensions

Remember: Tensors are the building blocks of PyTorch!